version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb-task-manager
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    container_name: backend-task-manager
    ports:
      - "${PORT}:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=${MONGO_URL}

volumes:
  mongo-data:
